env.BUNDLE_VERSION="0.0.1-SNAPSHOT"

node('docker') {
  stage('GIT') {
    git 'https://github.com/fernandohackbart/bikeride-lagom.git'
  }
  stage('Deploy Bikeride') {
    sh '/opt/kubernetes/bin/kubectl delete -f Kubernetes/authentication-impl-statefulset.yml'
    sh '/opt/kubernetes/bin/kubectl delete -f Kubernetes/biker-impl-statefulset.yml'
    sh '/opt/kubernetes/bin/kubectl delete -f Kubernetes/track-impl-statefulset.yml'
    sh '/opt/kubernetes/bin/kubectl delete -f Kubernetes/ride-impl-statefulset.yml'
  }
  stage('Deploy Bikeride') {
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/authentication-impl-statefulset.yml'
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/biker-impl-statefulset.yml'
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/track-impl-statefulset.yml'
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/ride-impl-statefulset.yml'
  }
  stage('Deploy Bikeride') {
    sh '/opt/kubernetes/bin/kubectl get all -n default'
  }
}




