env.BUNDLE_VERSION="0.0.1-SNAPSHOT"

node('docker') {
  stage('GIT') {
    git 'https://github.com/fernandohackbart/bikeride-lagom.git'
  }
  stage('Deploy Cassandra') {
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/cassandra.yml'
  }
  stage('wait') {
    timeout(time:5, unit:'DAYS') {
      input message:'Cassandra ready?'
    }
  }
  stage('Start Kong database configuration') {
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/kong_migration_cassandra.yml'
  }
  stage('wait') {
    timeout(time:5, unit:'DAYS') {
      input message:'Kong database configuration ready?'
    }
  }
  stage('remove Kong database configuration job') {
    sh '/opt/kubernetes/bin/kubectl delete -f Kubernetes/kong_migration_cassandra.yml'
  }
  stage('Deploy Kong') {
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/kong_cassandra.yml'
  }
  stage('Deploy Bikeride') {
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/authentication-statefulset.yml'
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/biker-statefulset.yml'
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/track-statefulset.yml'
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/ride-statefulset.yml'
  }
  stage('Deploy Bikeride services') {
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/authentication-service.yml'
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/biker-service.yml'
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/track-service.yml'
    sh '/opt/kubernetes/bin/kubectl create -f Kubernetes/ride-service.yml'
  }
  stage('Deploy Bikeride') {
    sh '/opt/kubernetes/bin/kubectl get all -n default'
  }
}




