env.BUNDLE_VERSION="0.0.1-SNAPSHOT"

node('docker') {
  //stage('Docker login') {
  //  sh 'docker login'
  //}
  stage('Push images') {
    sh 'docker push bikeride/bikeride-backend:base'
    sh 'docker push bikeride/authentication-lagom-impl:${BUNDLE_VERSION}'
    sh 'docker push bikeride/biker-lagom-impl:${BUNDLE_VERSION}'
    sh 'docker push bikeride/track-lagom-impl:${BUNDLE_VERSION}'
    sh 'docker push bikeride/ride-lagom-impl:${BUNDLE_VERSION}'
  }
}
